name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Install dependencies
      uses: actions/checkout@v1
        sudo apt-get install build-essential libpixman-1-0 libpixman-1-dev libglib2.0-dev zlib1g-dev
    - name: Compile qemu
      run: |
        cd $HOME
        mkdir qemu_esp32
        cd qemu_esp32
        ../qemu-xtensa-esp32/configure --disable-capstone --disable-werror --prefix=`pwd`/root --target-list=xtensa-softmmu
        make -j 2
    - uses: actions/upload-artifact@master
      with:
        name: qemu-system-xtensa
        path: $HOME/xtensa-softmmu/qemu-system-xtensa
